# Generated by Django 4.2.2 on 2023-08-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Car decoration'), ('D', 'Device'), ('J', 'Jeans'), ('C', 'Cotton')], max_length=2),
        ),
    ]
