# Generated by Django 4.2.2 on 2023-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'Car decoration'), ('CS', 'Car serviceparts'), ('J', 'Jeans'), ('C', 'Cotton')], max_length=2),
        ),
    ]
